# Data Collection

In [1]:
import requests
import time
import pandas as pd

In [2]:
base_url = 'https://api.pushshift.io'
submission_endpt = '/reddit/submission/search'
comment_endpt = '/reddit/comment/search'

In [17]:
def pull_submission(topic, frequency):
    
    """
    Returns pulled submissions of a specific topic and frequency
    Merges all dataframes into one and saves final dataframe into the datasets folder
    Prints the length of each dataframe to confirm number of posts successfully pulled
    """
    
    import pandas as pd
    import requests

    base_url = 'https://api.pushshift.io'
    submission_endpt = '/reddit/submission/search'
    
    params = {
    'subreddit' : topic,
    'size': 100
    }
    
    req = requests.get(base_url + submission_endpt, params)
    report = req.json()
    posts = report['data']
    posts_df = pd.DataFrame(posts)
    
    length_list=[]
    length_list.append(len(report['data']))
    
    for i in range(1, frequency, 1):
        params = {
        'subreddit' : topic,
        'size': 100,
        'before': posts[-1]['created_utc']
        }
        
        req = requests.get(base_url + submission_endpt, params)
        report = req.json()
        posts = report['data']
        new_df = pd.DataFrame(posts)
        posts_df = pd.concat([posts_df,new_df], ignore_index=True)
        length_list.append(len(report['data']))
    
    posts_df.to_csv('../datasets/' + topic + '_submissions.csv', index=False)
    print(length_list)

In [64]:
def pull_comment(topic, frequency):
    
    """
    Returns pulled comments of a specific topic and frequency
    Merges all dataframes into one and saves final dataframe into the datasets folder
    Prints the length of each dataframe to confirm number of posts successfully pulled
    """
    
    import pandas as pd
    import requests

    base_url = 'https://api.pushshift.io'
    submission_endpt = '/reddit/comment/search'
    
    params = {
    'subreddit' : topic,
    'size': 100
    }
    
    req = requests.get(base_url + submission_endpt, params)
    report = req.json()
    posts = report['data']
    posts_df = pd.DataFrame(posts)
    
    length_list=[]
    length_list.append(len(report['data']))
    
    for i in range(1, frequency, 1):
        params = {
        'subreddit' : topic,
        'size': 100,
        'before': posts[-1]['created_utc']
        }
        
        req = requests.get(base_url + submission_endpt, params)
        report = req.json()
        posts = report['data']
        new_df = pd.DataFrame(posts)
        posts_df = pd.concat([posts_df,new_df], ignore_index=True)
        length_list.append(len(report['data']))
    
    posts_df.to_csv('../datasets/' + topic + '_comments.csv', index=False)
    print(length_list)

In [62]:
#pull_submission('gardening',35)

In [94]:
#pull_comment('hiking',25)

### Check out the data I pulled...

#### Hiking

In [2]:
hiking_df = pd.read_csv('../datasets/hiking_submissions.csv')

In [3]:
hiking_df[['subreddit', 'selftext', 'title']].head()

,subreddit,selftext,title
0,hiking,NaN,Boulder Flatiron Loop Hike
1,hiking,Anyone know any cool lakes to hike to that you...,Washington state lakes to swim
2,hiking,NaN,"Here's a fun episode, demonstrating why a fly-..."
3,hiking,NaN,Picture I took of my friend at Angel’s Landing...
4,hiking,NaN,Hiking to Bertha Peak via Cougar Crest Trail a...

In [4]:
hiking_df[hiking_df['title'] == '[REMOVED]']

Empty DataFrame
Columns: [all_awardings, allow_live_comments, author, author_flair_css_class, author_flair_richtext, author_flair_text, author_flair_type, author_fullname, author_patreon_flair, author_premium, awarders, can_mod_post, contest_mode, created_utc, domain, full_link, gallery_data, gildings, id, is_crosspostable, is_gallery, is_meta, is_original_content, is_reddit_media_domain, is_robot_indexable, is_self, is_video, link_flair_background_color, link_flair_richtext, link_flair_text_color, link_flair_type, locked, media_metadata, media_only, no_follow, num_comments, num_crossposts, over_18, parent_whitelist_status, permalink, pinned, pwls, retrieved_on, score, selftext, send_replies, spoiler, stickied, subreddit, subreddit_id, subreddit_subscribers, subreddit_type, thumbnail, thumbnail_height, thumbnail_width, title, total_awards_received, treatment_tags, upvote_ratio, url, url_overridden_by_dest, whitelist_status, wls, link_flair_css_class, link_flair_template_id, link_flair_text, media, media_embed, post_hint, preview, secure_media, secure_media_embed, removed_by_category, author_flair_background_color, author_flair_text_color, banned_by, author_cakeday, edited, crosspost_parent, crosspost_parent_list, gilded]
Index: []

[0 rows x 81 columns]

In [5]:
hiking_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 81 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   all_awardings                  5000 non-null   object
 1   allow_live_comments            5000 non-null   bool
 2   author                         5000 non-null   object
 3   author_flair_css_class         0 non-null      float64
 4   author_flair_richtext          4788 non-null   object
 5   author_flair_text              0 non-null      float64
 6   author_flair_type              4788 non-null   object
 7   author_fullname                4788 non-null   object
 8   author_patreon_flair           4788 non-null   object
 9   author_premium                 4788 non-null   object
 10  awarders                       5000 non-null   object
 11  can_mod_post                   5000 non-null   bool
 12  contest_mode                   5000 non-null   bool
 13  created_utc                    5000 non-null   int64
 14  domain                         5000 non-null   object
 15  full_link                      5000 non-null   object
 16  gallery_data                   990 non-null    object
 17  gildings                       5000 non-null   object
 18  id                             5000 non-null   object
 19  is_crosspostable               5000 non-null   bool
 20  is_gallery                     1140 non-null   object
 21  is_meta                        5000 non-null   bool
 22  is_original_content            5000 non-null   bool
 23  is_reddit_media_domain         5000 non-null   bool
 24  is_robot_indexable             5000 non-null   bool
 25  is_self                        5000 non-null   bool
 26  is_video                       5000 non-null   bool
 27  link_flair_background_color    0 non-null      float64
 28  link_flair_richtext            5000 non-null   object
 29  link_flair_text_color          5000 non-null   object
 30  link_flair_type                5000 non-null   object
 31  locked                         5000 non-null   bool
 32  media_metadata                 1024 non-null   object
 33  media_only                     5000 non-null   bool
 34  no_follow                      5000 non-null   bool
 35  num_comments                   5000 non-null   int64
 36  num_crossposts                 5000 non-null   int64
 37  over_18                        5000 non-null   bool
 38  parent_whitelist_status        5000 non-null   object
 39  permalink                      5000 non-null   object
 40  pinned                         5000 non-null   bool
 41  pwls                           5000 non-null   int64
 42  retrieved_on                   5000 non-null   int64
 43  score                          5000 non-null   int64
 44  selftext                       1010 non-null   object
 45  send_replies                   5000 non-null   bool
 46  spoiler                        5000 non-null   bool
 47  stickied                       5000 non-null   bool
 48  subreddit                      5000 non-null   object
 49  subreddit_id                   5000 non-null   object
 50  subreddit_subscribers          5000 non-null   int64
 51  subreddit_type                 5000 non-null   object
 52  thumbnail                      5000 non-null   object
 53  thumbnail_height               3696 non-null   float64
 54  thumbnail_width                3696 non-null   float64
 55  title                          5000 non-null   object
 56  total_awards_received          5000 non-null   int64
 57  treatment_tags                 5000 non-null   object
 58  upvote_ratio                   5000 non-null   float64
 59  url                            5000 non-null   object
 60  url_overridden_by_dest         4132 non-null   object
 61  whitelist_status               5000 non-null   object
 62  wls                            5000 non-null   int64
 63  link_flair_css_class           3802 non-null   object
 64  link_flair_template_id         2040 non-null   object
 65  link_flair_text                3802 non-null   object
 66  media                          426 non-null    object
 67  media_embed                    338 non-null    object
 68  post_hint                      2810 non-null   object
 69  preview                        2810 non-null   object
 70  secure_media                   426 non-null    object
 71  secure_media_embed             338 non-null    object
 72  removed_by_category            614 non-null    object
 73  author_flair_background_color  0 non-null      float64
 74  author_flair_text_color        212 non-null    object
 75  banned_by                      7 non-null      object
 76  author_cakeday                 23 non-null     object
 77  edited                         8 non-null      float64
 78  crosspost_parent               30 non-null     object
 79  crosspost_parent_list          30 non-null     object
 80  gilded                         2 non-null      float64
dtypes: bool(18), float64(9), int64(9), object(45)
memory usage: 2.5+ MB

In [6]:
hiking_df.head()

,all_awardings,allow_live_comments,author,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_type,author_fullname,author_patreon_flair,author_premium,...,secure_media_embed,removed_by_category,author_flair_background_color,author_flair_text_color,banned_by,author_cakeday,edited,crosspost_parent,crosspost_parent_list,gilded
0,[],False,volash,NaN,[],NaN,text,t2_15ff6bb9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],False,username_noo,NaN,[],NaN,text,t2_7rac7394,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],False,the_museum_of_us,NaN,[],NaN,text,t2_a2l4ato4,False,False,...,"{'content': '&lt;iframe width=""356"" height=""20...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],False,youngbean96,NaN,[],NaN,text,t2_8ab1m8lk,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],False,BackcountryRenegade,NaN,[],NaN,text,t2_b8t03jim,False,False,...,"{'content': '&lt;iframe width=""356"" height=""20...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
hiking_df['title'].value_counts()

Ture Dalar nature reserve, Uddevalla, Sweden                                           7
Table Rock Mountain SC                                                                 4
K2, Northern Areas, Pakistan                                                           4
Winter mountain forest (Switzerland, Kanton Schwyz)                                    3
First time in a while it’s been above 60° pluto and I made sure we took advantage      3
                                                                                      ..
Winter hike in Banff National Park, Alberta, Canada. With some Gorilla-shaped snow!    1
Marker 28 at Permian Reef Trail, Guadalupe Mountains NP, TX                            1
This late sunset over a glass like north Michigan Lake looked incredible               1
We call it a poo with a view. 10 out of 10. would poo again.                           1
Backbone state park, Iowa.                                                             1
Name: title, Length: 4877, dtype: int64

In [9]:
hiking_comments = pd.read_csv('../datasets/hiking_comments.csv')

In [10]:
hiking_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   all_awardings                    2000 non-null   object
 1   associated_award                 0 non-null      float64
 2   author                           2000 non-null   object
 3   author_flair_background_color    0 non-null      float64
 4   author_flair_css_class           0 non-null      float64
 5   author_flair_richtext            1982 non-null   object
 6   author_flair_template_id         0 non-null      float64
 7   author_flair_text                0 non-null      float64
 8   author_flair_text_color          18 non-null     object
 9   author_flair_type                1982 non-null   object
 10  author_fullname                  1982 non-null   object
 11  author_patreon_flair             1982 non-null   object
 12  author_premium                   1982 non-null   object
 13  awarders                         2000 non-null   object
 14  body                             2000 non-null   object
 15  collapsed_because_crowd_control  0 non-null      float64
 16  comment_type                     0 non-null      float64
 17  created_utc                      2000 non-null   int64
 18  gildings                         2000 non-null   object
 19  id                               2000 non-null   object
 20  is_submitter                     2000 non-null   bool
 21  link_id                          2000 non-null   object
 22  locked                           2000 non-null   bool
 23  no_follow                        2000 non-null   bool
 24  parent_id                        2000 non-null   object
 25  permalink                        2000 non-null   object
 26  retrieved_on                     2000 non-null   int64
 27  score                            2000 non-null   int64
 28  send_replies                     2000 non-null   bool
 29  stickied                         2000 non-null   bool
 30  subreddit                        2000 non-null   object
 31  subreddit_id                     2000 non-null   object
 32  top_awarded_type                 0 non-null      float64
 33  total_awards_received            2000 non-null   int64
 34  treatment_tags                   2000 non-null   object
 35  distinguished                    197 non-null    object
 36  author_cakeday                   2 non-null      object
dtypes: bool(5), float64(8), int64(4), object(20)
memory usage: 509.9+ KB

In [11]:
hiking_comments[['subreddit', 'body']].head()

  subreddit                                               body
0    hiking  Dang I tried a month ago the snow was super de...
1    hiking  \nI see you've posted an image.  Thanks for yo...
2    hiking  I can't tell what is more impressive: the wild...
3    hiking  This isn't part of  the Smokey Mountains. This...
4    hiking  I was just thinking about this the other day b...

In [12]:
#There are "deleted" comments so I have to clean my data and delete these rows.

hiking_comments[hiking_comments['body']== "[deleted]"]

,all_awardings,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,author_flair_type,...,score,send_replies,stickied,subreddit,subreddit_id,top_awarded_type,total_awards_received,treatment_tags,distinguished,author_cakeday
29,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
31,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
363,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
444,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
506,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
654,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,-1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
704,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
741,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
805,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,False,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
1202,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
1204,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
1518,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
1908,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN
1945,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1,True,False,hiking,t5_2r9om,NaN,0,[],NaN,NaN

In [13]:
hiking_comments['body'].value_counts()

\nI see you've posted an image.  Thanks for your contribution!\n\n*Did you included the* ***required*** *title information?*  **[Your text.] [Most Specific place], [Specific place], [General place], [COUNTRY].**  \n      \nIf you didn't include this information, please delete your post and resubmit it.  **Your post will be removed without warning if it does not follow this rule!**\n\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/hiking) if you have any questions or concerns.*    183
[deleted]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    14
r/hikersfriend                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               13
Thank you!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   13
Your post was removed due to your account being new. Please wait until your account is 1 day old before you post again. Or try messaging the moderators for approval.\n\n*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/hiking) if you have any questions or concerns.*                                                                                                                                                                                                                                 11
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
Just got married at the Temple of Sinawava a few weeks ago. Already wishing I could go back. Great pics!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
Such an underrated area!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
One of, actually probably my all time, favorite state.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Was certainly a highlight of the past year. Not something I'll forget soon. There's definitely something about being out on empty hills with a few close mates.                                                                                                                                                                                                                                                                                                                                                                                                                               1
I was there for New Years. 55° crowded                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: body, Length: 1735, dtype: int64

#### Gardening

In [14]:
gardening_df = pd.read_csv('../datasets/gardening_submissions.csv')

In [49]:
gardening_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 78 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   all_awardings                  3000 non-null   object
 1   allow_live_comments            3000 non-null   bool
 2   author                         3000 non-null   object
 3   author_flair_css_class         10 non-null     object
 4   author_flair_richtext          2996 non-null   object
 5   author_flair_text              92 non-null     object
 6   author_flair_type              2996 non-null   object
 7   author_fullname                2996 non-null   object
 8   author_patreon_flair           2996 non-null   object
 9   author_premium                 2996 non-null   object
 10  awarders                       3000 non-null   object
 11  can_mod_post                   3000 non-null   bool
 12  contest_mode                   3000 non-null   bool
 13  created_utc                    3000 non-null   int64
 14  domain                         3000 non-null   object
 15  full_link                      3000 non-null   object
 16  gildings                       3000 non-null   object
 17  id                             3000 non-null   object
 18  is_crosspostable               3000 non-null   bool
 19  is_meta                        3000 non-null   bool
 20  is_original_content            3000 non-null   bool
 21  is_reddit_media_domain         3000 non-null   bool
 22  is_robot_indexable             3000 non-null   bool
 23  is_self                        3000 non-null   bool
 24  is_video                       3000 non-null   bool
 25  link_flair_background_color    0 non-null      float64
 26  link_flair_richtext            3000 non-null   object
 27  link_flair_text_color          3000 non-null   object
 28  link_flair_type                3000 non-null   object
 29  locked                         3000 non-null   bool
 30  media_only                     3000 non-null   bool
 31  no_follow                      3000 non-null   bool
 32  num_comments                   3000 non-null   int64
 33  num_crossposts                 3000 non-null   int64
 34  over_18                        3000 non-null   bool
 35  parent_whitelist_status        3000 non-null   object
 36  permalink                      3000 non-null   object
 37  pinned                         3000 non-null   bool
 38  post_hint                      1655 non-null   object
 39  preview                        1655 non-null   object
 40  pwls                           3000 non-null   int64
 41  retrieved_on                   3000 non-null   int64
 42  score                          3000 non-null   int64
 43  selftext                       631 non-null    object
 44  send_replies                   3000 non-null   bool
 45  spoiler                        3000 non-null   bool
 46  stickied                       3000 non-null   bool
 47  subreddit                      3000 non-null   object
 48  subreddit_id                   3000 non-null   object
 49  subreddit_subscribers          3000 non-null   int64
 50  subreddit_type                 3000 non-null   object
 51  thumbnail                      3000 non-null   object
 52  thumbnail_height               2033 non-null   float64
 53  thumbnail_width                2033 non-null   float64
 54  title                          3000 non-null   object
 55  total_awards_received          3000 non-null   int64
 56  treatment_tags                 3000 non-null   object
 57  upvote_ratio                   3000 non-null   float64
 58  url                            3000 non-null   object
 59  url_overridden_by_dest         2354 non-null   object
 60  whitelist_status               3000 non-null   object
 61  wls                            3000 non-null   int64
 62  gallery_data                   637 non-null    object
 63  is_gallery                     666 non-null    object
 64  media_metadata                 667 non-null    object
 65  media                          48 non-null     object
 66  media_embed                    44 non-null     object
 67  secure_media                   48 non-null     object
 68  secure_media_embed             44 non-null     object
 69  author_flair_template_id       93 non-null     object
 70  author_flair_text_color        111 non-null    object
 71  removed_by_category            256 non-null    object
 72  crosspost_parent               37 non-null     object
 73  crosspost_parent_list          37 non-null     object
 74  author_cakeday                 7 non-null      object
 75  suggested_sort                 1 non-null      object
 76  author_flair_background_color  0 non-null      float64
 77  poll_data                      2 non-null      object
dtypes: bool(18), float64(5), int64(9), object(46)
memory usage: 1.4+ MB

In [87]:
gardening_df[gardening_df['title'] == '[deleted]']

Empty DataFrame
Columns: [all_awardings, allow_live_comments, author, author_flair_css_class, author_flair_richtext, author_flair_text, author_flair_type, author_fullname, author_patreon_flair, author_premium, awarders, can_mod_post, contest_mode, created_utc, domain, full_link, gildings, id, is_crosspostable, is_meta, is_original_content, is_reddit_media_domain, is_robot_indexable, is_self, is_video, link_flair_background_color, link_flair_richtext, link_flair_text_color, link_flair_type, locked, media_only, no_follow, num_comments, num_crossposts, over_18, parent_whitelist_status, permalink, pinned, post_hint, preview, pwls, retrieved_on, score, selftext, send_replies, spoiler, stickied, subreddit, subreddit_id, subreddit_subscribers, subreddit_type, thumbnail, thumbnail_height, thumbnail_width, title, total_awards_received, treatment_tags, upvote_ratio, url, url_overridden_by_dest, whitelist_status, wls, gallery_data, is_gallery, media_metadata, media, media_embed, secure_media, secure_media_embed, author_flair_template_id, author_flair_text_color, removed_by_category, crosspost_parent, crosspost_parent_list, author_cakeday, suggested_sort, author_flair_background_color, poll_data]
Index: []

In [51]:
gardening_df['title'].value_counts()

Twelverays | Digital Agency in Vancouver and Toronto                                                                                                                                                         6
To the infant everything is unique. - orange mady asarana                                                                                                                                                    4
Keno Lottery Cash - pasadena weddings                                                                                                                                                                        4
Vipslot77 Situs Judi Slot Online Joker123 dan Slot Pragmatic Play Terpercaya                                                                                                                                 4
SERP API - All SERP                                                                                                                                                                                          4
                                                                                                                                                                                                            ..
My Columbine is doing great after the freak snow storm we had this week. I’ve never had Columbine before and I’m excited to see how it grows! Do you have any new-to-you plants in your garden this year?    1
LPT: Frost dates are a joke. Don't trust them.                                                                                                                                                               1
Garden thieves get shamed                                                                                                                                                                                    1
🤣                                                                                                                                                                                                            1
What is the best way to move mint plants from yard to garden, with car ride in between.                                                                                                                      1
Name: title, Length: 2899, dtype: int64

In [15]:
gardening_comments = pd.read_csv('../datasets/gardening_comments.csv')

In [73]:
gardening_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   all_awardings                    2000 non-null   object
 1   associated_award                 0 non-null      float64
 2   author                           2000 non-null   object
 3   author_flair_background_color    0 non-null      float64
 4   author_flair_css_class           19 non-null     object
 5   author_flair_richtext            1966 non-null   object
 6   author_flair_template_id         156 non-null    object
 7   author_flair_text                167 non-null    object
 8   author_flair_text_color          221 non-null    object
 9   author_flair_type                1966 non-null   object
 10  author_fullname                  1966 non-null   object
 11  author_patreon_flair             1966 non-null   object
 12  author_premium                   1966 non-null   object
 13  awarders                         2000 non-null   object
 14  body                             2000 non-null   object
 15  collapsed_because_crowd_control  0 non-null      float64
 16  comment_type                     0 non-null      float64
 17  created_utc                      2000 non-null   int64
 18  gildings                         2000 non-null   object
 19  id                               2000 non-null   object
 20  is_submitter                     2000 non-null   bool
 21  link_id                          2000 non-null   object
 22  locked                           2000 non-null   bool
 23  no_follow                        2000 non-null   bool
 24  parent_id                        2000 non-null   object
 25  permalink                        2000 non-null   object
 26  retrieved_on                     2000 non-null   int64
 27  score                            2000 non-null   int64
 28  send_replies                     2000 non-null   bool
 29  stickied                         2000 non-null   bool
 30  subreddit                        2000 non-null   object
 31  subreddit_id                     2000 non-null   object
 32  top_awarded_type                 0 non-null      float64
 33  total_awards_received            2000 non-null   int64
 34  treatment_tags                   2000 non-null   object
 35  author_cakeday                   10 non-null     object
dtypes: bool(5), float64(5), int64(4), object(22)
memory usage: 494.3+ KB

In [74]:
gardening_comments[['subreddit', 'body']].head()

   subreddit                                               body
0  gardening  It would be quite a beautifully diverse commun...
1  gardening  No! My strawberries are blooming too. I get sp...
2  gardening  IF they are first year strawberries. You can c...
3  gardening  I have found the same info, I was hoping you c...
4  gardening  I was so thrilled to see my hollyhocks are com...

In [16]:
#There are "deleted" comments so I have to clean my data and delete these rows.

gardening_comments[gardening_comments['body']== "[deleted]"]

,all_awardings,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_template_id,author_flair_text,author_flair_text_color,author_flair_type,...,retrieved_on,score,send_replies,stickied,subreddit,subreddit_id,top_awarded_type,total_awards_received,treatment_tags,author_cakeday
60,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619225965,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
248,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619220212,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
255,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619219823,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
257,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619219759,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
311,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619217591,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
353,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619216161,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
384,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619215324,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
396,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619214949,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
524,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619211355,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
550,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619210781,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
599,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619208829,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
822,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619200761,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
847,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619199701,1,False,False,gardening,t5_2qhkh,NaN,0,[],NaN
892,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619198465,1,False,False,gardening,t5_2qhkh,NaN,0,[],NaN
927,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619196989,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1076,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619192519,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1264,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619186379,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1271,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619186088,2,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1289,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619185667,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1339,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619184060,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1344,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619183945,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1350,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619183803,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1477,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619176886,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1639,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619170008,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1775,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619165903,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1812,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619165090,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1814,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619165076,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1865,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619163487,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
1991,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619159769,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
2034,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619159226,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
2158,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619156475,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
2449,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619148988,2,True,False,gardening,t5_2qhkh,NaN,0,[],NaN
2499,[],NaN,[deleted],NaN,NaN,NaN,NaN,NaN,dark,NaN,...,1619147099,1,True,False,gardening,t5_2qhkh,NaN,0,[],NaN

What do I have so far?

1. Hiking
    - 5,000 submissions
    - 2,000 comments
2. Gardening
    - 3,000 submissions
    - 2,500 comments